CREATE TABLE [dar].[ZDEFECT_TABLE](
	[MANDT] [int] NULL,
	[DATE_DEFECT] [bigint] NULL,
	[MATNR] [bigint] NULL,
	[MAKTX] [nvarchar](max) NULL,
	[BEZEI] [nvarchar](max) NULL,
	[LABST] [int] NULL,
	[INSME] [int] NULL,
	[PRCEH] [int] NULL,
	[PLNMG] [int] NULL,
	[ENTMG] [int] NULL,
	[MENGE] [int] NULL,
	[OMENG] [int] NULL,
	[ZQUAN] [int] NULL,
	[VTPLA] [int] NULL,
	[DEFECT] [nvarchar](max) NULL,
	[STOCK] [numeric](18, 2) NULL,
	[DEFECT_ALT] [nvarchar](max) NULL,
	[DATE_OUT] [bigint] NULL,
	[DATE_FINISH] [bigint] NULL,
	[DATE_AVAILABLE] [bigint] NULL,
	[MENGE_SERIES] [int] NULL,
	[MENGE_7] [int] NULL,
	[MENGE_14] [int] NULL,
	[ORDERED] [int] NULL,
	[PRICE] [numeric](18, 2) NULL
)