CREATE TABLE [dbo].[fact_shipment]
(
	[ДатВідвант] DATE,
	[Дата факт.] DATE,
	[Рік] INT,
	[Місяць] INT,
	[Чверть] INT,
	[ТТН] int,
	[КодТовару] INT,
	[Найменування товару] nvarchar(max),
	[Замовник] INT,
	[Клієнт] nvarchar(max),
	[Краiна] nvarchar(max),
	[Назва] nvarchar(max), 
	[КЗ] int,
	[Канал збуту] nvarchar(max),
	[Департ.] nvarchar(max),
	[Reprsez] nvarchar(max),
	[Обс.пост.] FLOAT,
	[ЕИ] nvarchar(max),
	[Сума без ПДВ] FLOAT,
	[Податок] FLOAT,
	[Сума з ПДВ] FLOAT,
	[Валют] nvarchar(max),
	[СумаБезПДВгрн] FLOAT,
	[Подат.грн] FLOAT,
	[СумаЗПДВ грн] FLOAT,
	[Відтермін.] INT,
	[№ контр.] nvarchar(max),
	[КодГрМат] INT,
	[Опис гр.матер.] nvarchar(max), 
	РЗ nvarchar(max),
	[Отримувач] nvarchar(max)
)