CREATE TABLE [dbo].[Products]
(
	[PRODUCTID] nvarchar(max),
	[CODE] nvarchar(max),
	[PRODUCTTYPEID] nvarchar(max),
	[GROUPID] nvarchar(max),
	[Базовая ед.] nvarchar(max),
	[PRODUCERCODE] nvarchar(max),
	[BRANDID_2LEV] nvarchar(max),
	[GOODS] nvarchar(max),
	[UNITCODE_2LEV] nvarchar(max),
	[MANAGERCODE] nvarchar(max),
	[NAMEM] nvarchar(max),
	[BU_2LEV] nvarchar(max),
	[AM] nvarchar(max),
	[MATERIALGROUPS] nvarchar(max),
	[BRANDNAME_2LEV] nvarchar(max),
	[UNITNAME_2LEV] nvarchar(max),
	[BU_FIRSTLEV] nvarchar(max),
	[PLANOVIK] nvarchar(max),
	[GROUPBUY] nvarchar(max),
	[NAME_ELEMENT] nvarchar(max),
	[NAME_OF_PROD] nvarchar(max),
	[NAME_OF_MATER] nvarchar(max),
	[CODE_BRAND_1LEV] nvarchar(max),
	[NAME_BRAND_1LEV] nvarchar(max),
	[Метка удаления] nvarchar(max),
	[DATUM] date,
	[Продажная ед.] nvarchar(max),
	[MVGR1] nvarchar(max),
	[MVGR2] nvarchar(max),
	[MVGR3] nvarchar(max),
	[MVGR4] nvarchar(max),
	[MVGR5] nvarchar(max),
	[Код Морион] nvarchar(max),
	[ATC_5] float,
	[Planned] nvarchar(max),
	[BU] nvarchar(max)
)
