create table Stage.Credit_temp
(
    [Бал.од] int,
    [Дата звіту] nvarchar(max),
    [Рах.ГК] nvarchar(max),
	[Довг.тек.рах.гол.кн.] nvarchar(max),
	[МСФО кат.] nvarchar(max),
	[МСФО вид] nvarchar(max),
	[Контрагент] nvarchar(max),
	[Назва контрагенту] nvarchar(max),
	[Тип рахун.] nvarchar(max),
	[Пос.рах.] nvarchar(max),
	[Рік] int,
	[Ном.док] NVARCHAR(max),
	[Фінанс.рік] int,
	[Поз.] int,
	[Дата док.] nvarchar(max),
	[Дата пров.] nvarchar(max),
	[Вирівнюв.] nvarchar(max),
	[Дата догов] nvarchar(max),
	[Номер договору] nvarchar(max),
	[Дат.погаш.] nvarchar(max),
	[Вік заборг] nvarchar(max),
	[дні простр] nvarchar(max),
	[Валюта] nvarchar(max),
	[Сума] nvarchar(max),
	[Сума у внутр.в.] nvarchar(max),
	[Валюта1] nvarchar(max),
	[СумПогЗвіт] nvarchar(max),
	[Ср%ст.деп] float,
	[Уяв%дохід] nvarchar(max),
	[Тип валюти] int,
	[Ном.стр.] int
	   )