CREATE TABLE Stage.Debit_Temp
(
	[Бал.од] nvarchar(max),
	[Дата звіту] nvarchar(max),
	[Рах.ГК] nvarchar(max),
	[Довг.тек.рах.гол.кн.] nvarchar(max),
	[МСФО кат.] nvarchar(max),
	[МСФО вид] nvarchar(max),
	[Контрагент] nvarchar(max),
	[Назва контрагенту] nvarchar(max),
	[Тип рахун.] nvarchar(max),
	[Пос.рах.] nvarchar(max),
	[Рік] nvarchar(max),
	[Ном.док] nvarchar(max),
	[Фінанс.рік] nvarchar(max),
	[Поз.] nvarchar(max),
	[Дата док.] nvarchar(max) ,
	[Дата пров.] nvarchar(max),
	[Вирівнюв.] nvarchar(max),
	[Дата догов] nvarchar(max),
	[Номер договору] nvarchar(max),
	[Дат.погаш.] nvarchar(max),
	[Вік заборг] nvarchar(max),
	[дні простр] nvarchar(max),
	[Валюта] nvarchar(20),
	[Сума] nvarchar(max),
	[Сума у внутр.в.] nvarchar(max),
	[Валюта1] nvarchar(max),
	[СумПогЗвіт] nvarchar(max),
	[Ср%ст.деп] nvarchar(max),
	[Уяв%дохід] nvarchar(max),
	[Тип валюти] nvarchar(max),
	[Ном.стр.] nvarchar(max),
)
