CREATE TABLE [stage].[fact_shipment]
(
	[ДатВідвант] nvarchar(max),
	[Дата факт.] nvarchar(max),
	[Рік] nvarchar(max),
	[Місяць] nvarchar(max),
	[Чверть] nvarchar(max),
	[ТТН] int,
	[КодТовару] nvarchar(max),
	[Найменування товару] nvarchar(max),
	[Замовник] nvarchar(max),
	[Клієнт] nvarchar(max),
	[Краiна] nvarchar(max),
	[Назва] nvarchar(max), 
	[КЗ] int,
	[Канал збуту] nvarchar(max),
	[Департ.] nvarchar(max),
	[Reprsez] nvarchar(max),
	[Обс.пост.] nvarchar(max),
	[ЕИ] nvarchar(max),
	[Сума без ПДВ] nvarchar(max),
	[Податок] nvarchar(max),
	[Сума з ПДВ] nvarchar(max),
	[Валют] nvarchar(max),
	[СумаБезПДВгрн] nvarchar(max),
	[Подат.грн] nvarchar(max),
	[СумаЗПДВ грн] nvarchar(max),
	[Відтермін.] nvarchar(max),
	[№ контр.] nvarchar(max),
	[КодГрМат] nvarchar(max),
	[Опис гр.матер.] nvarchar(max), 
	РЗ nvarchar(max),
	[Отримувач] nvarchar(max)
)
