CREATE TABLE Stage.fact_qlik_temp (
postingDate NCHAR(10) NULL
,material NVARCHAR(500) NULL
,qty NVARCHAR(50) NULL
,currency NCHAR(50) NULL
,PRICE_CURR NVARCHAR(50) NULL
,SUM_CURR NVARCHAR(50) NULL
,PRICE_UAH NVARCHAR(50) NULL
,SUM_UAH NVARCHAR(50) NULL
,accountingType NVARCHAR(200) NULL
)