CREATE TABLE [stage].[fact_shipment]
(
	[ДатВідвант] nvarchar(max),
	[Дата факт.] nvarchar(max),
	[Рік] int,
	[Місяць] int,
	[Чверть] int,
	[ТТН] int,
	[КодТовару] int,
	[Найменування товару] nvarchar(max),
	[Замовник] int,
	[Клієнт] nvarchar(max),
	[Краiна] nvarchar(max),
	[Назва] nvarchar(max), 
	[КЗ] int,
	[Канал збуту] nvarchar(max),
	[Департ.] nvarchar(max),
	[Reprsez] nvarchar(max),
	[Обс.пост.] nvarchar(max),
	[ЕИ] nvarchar(max),
	[Сума без ПДВ] nvarchar(max),
	[Податок] nvarchar(max),
	[Сума з ПДВ] nvarchar(max),
	[Валют] nvarchar(max),
	[СумаБезПДВгрн] nvarchar(max),
	[Подат.грн] nvarchar(max),
	[СумаЗПДВ грн] nvarchar(max),
	[Відтермін.] int,
	[№ контр.] nvarchar(max),
	[КодГрМат] int,
	[Опис гр.матер.] nvarchar(max),
	РЗ nvarchar(max),
	[Отримувач] nvarchar(max)
)
