CREATE TABLE Stage.plan_temp (
VER_PLAN NVARCHAR(50) NULL
,Year NVARCHAR(10) NULL
,MonthNum NVARCHAR(10) NULL
,MATERIAL NVARCHAR(2000) NULL
,QTY NVARCHAR(50) NULL
,CURR NVARCHAR(50) NULL
,SUM_CURR NVARCHAR(50) NULL
,SUM_UAH NVARCHAR(50) NULL
,PRICE_CURR_AE NVARCHAR(50) NULL
,PRICE_UAH_AE NVARCHAR(50) NULL
,ACCOUNT_N NVARCHAR(50) NULL
)