CREATE TABLE [Stage].[ZPP070224]
(
	[Наименован] nvarchar(max),
	[Код ресурса] nvarchar(max),
	[Номер заказа] nvarchar(max),
	[Материал] nvarchar(max),
	[Наименование материала] nvarchar(max),
	[Серия] nvarchar(max),
	[Текст операции] nvarchar(max),
	[Дата завершення] nvarchar(max),
	[Количество] nvarchar(max),
	[Количество1] nvarchar(max),
	[Количество2] nvarchar(max),
	[ЕИ] nvarchar(max),
	[Общее время работы ресурса] nvarchar(max),
	[Время на переналадки] nvarchar(max),
	[Время перехода на след серию] nvarchar(max),
	[Время на производство] nvarchar(max),
	[Плановая производительность] nvarchar(max),
	[Коеф пересчета] nvarchar(max),
	[Общая эффективность] nvarchar(max),
	[Эффективность без учета] nvarchar(max),
	[Производительность] nvarchar(max),
	[Качество] nvarchar(max),
	[Доступность] nvarchar(max),
	[Доступность Д1] nvarchar(max),
	[Доступность Д2] nvarchar(max),
	[Доступность Д3] nvarchar(max)
)
