CREATE TABLE Finance.Debit
(
	[Бал.од] int,
	[Дата звіту] date,
	[Рах.ГК] bigint,
	[Довг.тек.рах.гол.кн.] nvarchar(max),
	[МСФО кат.] nvarchar(max),
	[МСФО вид] nvarchar(max),
	[Контрагент] nvarchar(max),
	[Назва контрагенту] nvarchar(max),
	[Тип рахун.] nvarchar(max),
	[Пос.рах.] bigint,
	[Рік] int,
	[Ном.док] bigint,
	[Фінанс.рік] int,
	[Поз.] int,
	[Дата док.] date ,
	[Дата пров.] date,
	[Вирівнюв.] date,
	[Дата догов] date,
	[Номер договору] nvarchar(max),
	[Дат.погаш.] date,
	[Вік заборг] int,
	[дні простр] int,
	[Валюта] nvarchar(20),
	[Сума] numeric(18,2),
	[Сума у внутр.в.] numeric(18,2),
	[Валюта1] nvarchar(20),
	[СумПогЗвіт] numeric(18,2),
	[Ср%ст.деп] int,
	[Уяв%дохід] numeric(18,2),
	[Тип валюти] int,
	[Ном.стр.] int,
)
